SELECT * FROM Users;
SELECT * FROM Client;
SELECT * FROM Vessel;
SELECT * FROM Cargo;
SELECT * FROM Shipment;
SELECT * FROM Docking_Bay;
SELECT * FROM Shipment;
SELECT * FROM Payment;
SELECT * FROM Notification;
